name: WEB Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./calculadoradeinvestimentos/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: './calculadoradeinvestimentos/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: "build"
          path: ./calculadoradeinvestimentos/out
          retention-days: 14
